### ISSUE TITLE
Korea KT Volte not work

### ISSUE THREAD

**Issue by aleksei74** [PixelExperience/vendor_aosp#8]
Fix apn-conf.xml for KT volte work.

https://github.com/PixelExperience/vendor_aosp/blob/pie-caf/prebuilt/common/etc/apns-conf.xml#L2982
https://github.com/PixelExperience/vendor_aosp/blob/pie/prebuilt/common/etc/apns-conf.xml#L2982

from:
apn carrier="KT IMS" mcc="450" mnc="08" apn="IMS" type="ims" protocol="IP" 

to:
apn carrier="KT IMS" mcc="450" mnc="08" apn="IMS" type="ims" protocol="IPV4V6" 

reference site: 
https://android.googlesource.com/device/sample/+/refs/tags/android-9.0.0_r35/etc/apns-full-conf.xml#25304

**Comment by jhenrique09** [comment]
send patch to lineage gerrit
